### ISSUE TITLE
how can I add this globaly

### ISSUE THREAD

**Issue by veso266** [Bellisario/hostname-patcher#5]
Hi you did wonderfull work, thank you

was wonderin if there is any way to somehow add this globaly
because right now I need to add this ontop of every project and it gets confusing for people that don't have the os.gethostname problem because they are running an os where GetHostName is supported and since node will probably never add the solution proposed here: https://github.com/nodejs/node/issues/40353

we need to figure out some more global aproach I guess

I know that a longterm solution for window7 will probably be this: https://github.com/vxiiduu/VxKex

So yea, hope you are allright

**Comment by Bellisario** [comment]
Hi, I'm happy you like the project!

I just tried overriding the built-in `os` module by linking to an example project a custom `os` named module, but I failed, [as expected](https://stackoverflow.com/a/14204911/14997578):

> Node has several modules compiled into the binary. These modules are described in greater detail elsewhere in this documentation.\
\
The core modules are defined in node's source in the lib/ folder.\
\
Core modules are always preferentially loaded if their identifier is passed to require(). For instance, require('http') will always return the built in HTTP module, even if there is a file by that name.

It's currently impossible to keep a JS project code unchanged and injecting the patch at the same time, because built-in modules always have priority over code inside `node_modules`.

I'll close the issue as not planned for now, but in case of new solutions to overcome the problem, I'm open to implement a global version of `hostname-patcher`!

---

P.S.: thanks for sharing the Windows 7 DLL patcher project, I didn't know the existence of something like that!
